config/routes.rb
RapidFTR::Application.routes.draw do

  match '/' => 'home#index', :as => :root, :via => :get

#######################
# USER URLS
#######################

  resources :users do
    collection do
      get :change_password
      get :unverified
      post :update_password
      post :register_unverified
      get :contact
    end
  end

  resources :sessions, :except => :index
  match 'login' => 'sessions#new', :as => :login, :via => [:post, :get, :put, :delete]
  match 'logout' => 'sessions#destroy', :as => :logout, :via => [:post, :get, :put, :delete]
  match '/active' => 'sessions#active', :as => :session_active, :via => [:post, :get, :put, :delete]

  resources :user_preferences
  resources :password_recovery_requests, :only => [:new, :create]
  match 'password_recovery_request/:password_recovery_request_id/hide' => 'password_recovery_requests#hide', :as => :hide_password_recovery_request, :via => :delete

  resources :devices
  match 'devices/update_blacklist' => 'devices#update_blacklist', :via => :post

  resources :roles
  match 'admin' => 'admin#index', :as => :admin, :via => [:post, :get, :put, :delete]
  match 'admin/update' => 'admin#update', :as => :admin_update, :via => [:post, :get, :put, :delete]


#######################
# CHILD URLS
#######################

  resources :children do
    collection do
      post :sync_unverified
      post :reindex
      get :advanced_search
      get :search
    end

    resources :attachments, :only => :show
    resource :duplicate, :only => [:new, :create]
  end

  match '/children-ids' => 'child_ids#all', :as => :child_ids, :via => [:post, :get, :put, :delete]
  match '/children/:id/photo/edit' => 'children#edit_photo', :as => :edit_photo, :via => :get
  match '/children/:id/photo' => 'children#update_photo', :as => :update_photo, :via => :put
  match '/children/:child_id/photos_index' => 'child_media#index', :as => :photos_index, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photos' => 'child_media#manage_photos', :as => :manage_photos, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/audio(/:id)' => 'child_media#download_audio', :as => :child_audio, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo/:photo_id' => 'child_media#show_photo', :as => :child_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo' => 'child_media#show_photo', :as => :child_legacy_photo, :via => [:post, :get, :put, :delete]
  match 'children/:child_id/select_primary_photo/:photo_id' => 'children#select_primary_photo', :as => :child_select_primary_photo, :via => :put
  match '/children/:child_id/resized_photo/:size' => 'child_media#show_resized_photo', :as => :child_legacy_resized_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo/:photo_id/resized/:size' => 'child_media#show_resized_photo', :as => :child_resized_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/thumbnail(/:photo_id)' => 'child_media#show_thumbnail', :as => :child_thumbnail, :via => [:post, :get, :put, :delete]
  match '/children' => 'children#index', :as => :child_filter, :via => [:post, :get, :put, :delete]


#######################
# API URLS
#######################

  namespace :api do
    controller :form_sections, :defaults => { :format => :json } do
      get 'form_sections', :action => :index
    end

    controller :device, :defaults => { :format => :json} do
      get 'is_blacklisted', :action => 'is_blacklisted'
      get 'is_blacklisted/:imei', :action => 'is_blacklisted'
    end

    controller :sessions, :defaults => {:format => :json} do
      post :login
      post :register
      post :logout
    end

    # CHILDREN

    resources :children do
      collection do
        get :ids, :defaults => {:format => :json}
        post :unverified, :defaults => {:format => :json}
      end

      member do
        controller :child_media do
          get 'photo(/:photo_id)', :action => 'show_photo'
          get 'audio(/:audio_id)', :action => 'download_audio'
        end
      end
    end

    # ENQUIRIES

    resources :enquiries, :defaults => {:format => :json}

  end

  # Backwards compatibility with 1.2
  match '/published_form_sections', :to => 'api/form_sections#index', :via => [:post, :get, :put, :delete]

#######################
# FORM SECTION URLS
#######################

  resources :form_sections, :path => 'form_section', :controller => 'form_section' do
    collection do
      match 'save_order', :via => [:post, :get, :put, :delete]
      match 'toggle', :via => [:post, :get, :put, :delete]
    end

    resources :fields, :controller => 'fields' do
      collection do
        post 'save_order'
        post 'delete'
        post 'toggle_fields'
        post 'change_form'
      end
    end
  end

  resources :highlight_fields do
    collection do
      post :remove
    end
  end


#######################
# ADVANCED SEARCH URLS
#######################

  match 'advanced_search/index', :to => 'advanced_search#index', :via => [:post, :get, :put, :delete]
  match 'advanced_search/export_data' => 'advanced_search#export_data', :as => :export_data_children, :via => :post


#######################
# LOGGING URLS
#######################

  resources :system_logs, :only => :index
  match '/children/:id/history' => 'child_histories#index', :as => :child_history, :via => :get
  match '/users/:id/history' => 'user_histories#index', :as => :user_history, :via => :get


#######################
# REPLICATION URLS
#######################

  resources :replications, :path => "/devices/replications" do
    collection do
      post :configuration
    end

    member do
      post :start
      post :stop
    end
  end

  resources :system_users, :path => "/admin/system_users"

#######################
# REPORTING URLS
#######################
  resources :reports, :only => [:index, :show]

#######################
# TESTING URLS
#######################
  if (Rails.env.android? || Rails.env.test? || Rails.env.development? || Rails.env.cucumber?)
    match 'database/delete_data/:data_type' => 'database#delete_data', :as => :reset_data, :via => :delete
    match 'database/reset_fieldworker' => 'database#reset_fieldworker', :as => :reset_fieldworker, :via => :delete
  end

end

app/views/shared/_add_translations.html.erb
<div class="translation">
  <% if show_drop_down %>
    <div class="lang_title"><%= t(:provide_translation) %>
      <%= select_tag("locale", options_for_select(RapidFTR::Application::LOCALES_WITH_DESCRIPTION.select { |option| option[1] != I18n.default_locale.to_s }), :class => 'locale') %>
    </div>
  <% end %>
  <% RapidFTR::Application::LOCALES.each do |given_locale| %>
      <% if I18n.default_locale.to_s != given_locale %>
        <div class="<%= "translation_forms #{given_locale}"%> hide">
          <%= render :partial => 'shared/fields', :locals => {:fields => fields, :f => f, :given_locale => given_locale}%>
        </div>
      <% end %>
  <% end %>
</div>

app/views/shared/_fields.html.erb
<fieldset>
  <% fields.each do |field_hash| %>
      <div>
      <label class="key"><%= t(field_hash.keys.first.to_sym, :locale => given_locale.to_sym) %></label>
      <%= f.send "#{field_hash.values.first}", "#{field_hash.keys.first}_#{given_locale}".to_sym %>
      </div>
<% end %>
</fieldset>

app/views/shared/_form_fields.html.erb
<div class="form-fields-container hide">
  <div class="criteria_menu">
  <a class='close-link'><%= image_tag("dialog-close.png") %></a>
  <div class='box-shadow content'>

      <% @forms.each do|form|%>
        <ul id="fields-for-form-<%= form.id%>" class="fields" data-id="<%= form.unique_id %>">
          <% form.fields.each do |field| %>
              <% if field.visible? %>
                <li id="field-<%= field.name%>" data-name="<%= field.name %>"><%= field.display_name %></li>
              <% end %>

          <%end%>
        </ul>
      <%end%>

    <ul class="forms">
        <% @forms.each do|form| %>
          <li id="form-<%= form.id%>" class="form">
            <%= form.name %>
          </li>
        <%end%>
    </ul>
  <div>
</div>

<script>

        $("ul.forms li:first, ul.fields:first").addClass('selected');

        $(".add_field").click(function(){
            $(".form-fields-container").toggleClass("hide");
        });

        $("ul.forms li").click(function(){
            $("ul.forms li").removeClass("selected");
            $(this).addClass("selected");
            var item = $(this).attr("id");
            var list = "fields-for-" + item;
            $("ul.fields").removeClass("selected");
            $("#" + list).addClass("selected");

        });

        $(".close-link").click(function(){
            $(".form-fields-container").addClass("hide");
        });

        $("ul.fields li").click(function() {
          var form_id = $(this).parents("ul").attr("data-id");
          var name = $(this).data("name");
          updateWithSelectedItem({
            field_name: name,
            form_id : form_id
          });
        });
</script>
 </div>
    </div>
    </div>

app/views/shared/_header_links.html.erb
<div class="links">

  <% unless current_user.nil? %>

    <%= t("header.welcome") %> <%= current_user.user_name %>,
    <%= link_with_confirm t("header.logout"), logout_path %> |
    <%= link_with_confirm t("header.my_account"), user_path(current_user.id) %> |

    <% if can?(:manage, SystemUsers) or can?(:highlight, Field) %>
      <%= link_to t("header.system_settings"), admin_path %> |
    <% end %>
  <% end %>

  <%= link_with_confirm t("header.contact"), contact_users_path %>

</div>

app/views/shared/_pagination.html.erb
<% results ||= WillPaginate::Collection.new 1,1,0 %>

<div class="pagination-box">
  <div class="page_info"><%= page_entries_info results %></div>
  <%= will_paginate results %>
  <div class="clearfix"></div>
</div>

app/views/shared/_participate.html.erb
<div class='participation'>
  <h2>Participate</h2>

  <p>We are looking for experienced Ruby on Rails programmers. If you're interested in participating, please
    <a href="/">contact us</a>
  </p>
</div>

app/views/shared/_side_tab.html.erb
 <div class="side-tab">
    <ul>
      <li class=<%= (highlight_page == 'users' ? 'current' : '') %>><%= link_to I18n.t("users.label"), users_path if can?(:read, User)%></li>
      <li class=<%= (highlight_page == 'unverified' ? 'current' : '') %>>
      	<%= link_to I18n.t("users.unverified"), unverified_users_path if can?(:show, User)  %></li>
      <li class=<%= (highlight_page == 'roles' ? 'current' : '') %>>
      	<%= link_to t("roles.label"), roles_path if can?(:index, Role) %></li>
    </ul>
 </div>

app/views/shared/_sidebar.html.erb
<div class="profile-image">
  <% unless @child.photos.blank? %>
      <div class='image'>
        <%= link_to image_tag(child_resized_photo_path(@child, @child.primary_photo_id, 328, :ts => @child.last_updated_at), :alt => 'Profile Image'), child_resized_photo_path(@child, @child.primary_photo_id, 640)%>
        <p class='view-full-size'><%= t("child.messages.see_full_size") %> </p>
      </div>
      <% if can? :edit, @child %>
          <%= link_to(t("child.edit_photo"), edit_photo_url(@child), :class=>"edit_photo") %>
          <%= link_to(t("child.manage_photos"), manage_photos_url(@child), :class=>"manage_photo") %>
      <% end %>
  <% else %>
      <%= image_tag('no_photo_clip.jpg') %>
  <% end %>
</div>

app/views/shared/error_response.html.erb
<h1><%= exception.status_text %></h1>
<h2><%= exception.message %></h2>